# Site settings
title: Genability Documentation
email: support@genability.com
description: > # this means to ignore newlines until "baseurl:"
 This site contains documentation, how-tos, tutorials, client libraries,
 and sample code related to Genability's APIs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: genability
github_username:  Genability

# Build settings
markdown: redcarpet