name: GitLeaks
on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: gitleaks
    uses: ArcadiaPower/security/.github/workflows/gitleaks.yaml@6aa1dcb98f556d9b902340fe5b6a231c310363c5
    secrets: inherit

